/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AirTicketReservationSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class frmRecipMain extends javax.swing.JInternalFrame {

    Connection dbcon=null;
    
    public frmRecipMain() {
        initComponents();
        dbcon = dbConnectr.Connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblrecipID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRecipName = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddNewCust = new javax.swing.JButton();
        btnViewCustomer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlights = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnReserveTickets = new javax.swing.JButton();
        btnCancelTickets = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Reciption ID :");

        lblrecipID.setForeground(new java.awt.Color(0, 102, 204));
        lblrecipID.setText("not logged in");
        lblrecipID.setToolTipText("Account Settings");
        lblrecipID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblrecipID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblrecipIDMouseClicked(evt);
            }
        });

        jLabel3.setText("Name :");

        lblRecipName.setText("not logged in");

        lblLogout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(0, 102, 204));
        lblLogout.setText("Logout");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrecipID)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRecipName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblrecipID)
                    .addComponent(jLabel3)
                    .addComponent(lblRecipName)
                    .addComponent(lblLogout))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAddNewCust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconAddUser.png"))); // NOI18N
        btnAddNewCust.setText("   Add New Customer");
        btnAddNewCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCustActionPerformed(evt);
            }
        });

        btnViewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconViewUser.png"))); // NOI18N
        btnViewCustomer.setText("   View Customers     ");
        btnViewCustomer.setPreferredSize(new java.awt.Dimension(89, 23));
        btnViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddNewCust, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddNewCust, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFlights);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnReserveTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconReserveTicket.png"))); // NOI18N
        btnReserveTickets.setText("   Reserve Tickets");
        btnReserveTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveTicketsActionPerformed(evt);
            }
        });

        btnCancelTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconViewTickets.png"))); // NOI18N
        btnCancelTickets.setText("   View Tickets       ");
        btnCancelTickets.setPreferredSize(new java.awt.Dimension(89, 23));
        btnCancelTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTicketsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReserveTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReserveTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getFlightinfo(){
        String SQL = "select flightID as 'Flight ID', planeID as 'Plane ID', source as 'Source', destination as 'Destination', dep_time as 'Departure Time', price as 'Basic Price' from flight_info";
        try{
            Statement stmnt = dbcon.createStatement();
            ResultSet rs = stmnt.executeQuery(SQL);
            this.tblFlights.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Cannot Retrieve flight data", "Database Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        MDIForm.loggedin=false;
        MDIForm.loggedUserID="";
        String loggedUserAccess="";
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        this.title = "Air Ticket Reservation System - Logged in as : "+MDIForm.loggedUserID+"";
        this.lblrecipID.setText(MDIForm.loggedUserID);
        String SQL = "select * from userinfo";
        try{
            Statement stmnt = dbcon.createStatement();
            ResultSet rs = stmnt.executeQuery(SQL);
            
            while(rs.next()){
                if(rs.getString("userID").equals(MDIForm.loggedUserID)){
                    this.lblRecipName.setText(rs.getString("fname")+" "+rs.getString("lname"));
                    break;
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Databse Connection Failed", "Database Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        getFlightinfo();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnReserveTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveTicketsActionPerformed
        if(MDIForm.frmNewCustActive==false){
            frmReserveTickets rt = new frmReserveTickets();
            MDIForm.DesktopPane.add(rt);
            int height = MDIForm.DesktopPane.getHeight();
            int width = MDIForm.DesktopPane.getWidth();
            int x = (int)(height-rt.getHeight())/2;
            int y = (int)(width-rt.getWidth())/2;
            rt.setLocation(y,x);
            rt.setVisible(true);
        }
    }//GEN-LAST:event_btnReserveTicketsActionPerformed

    private void btnCancelTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTicketsActionPerformed
        if(MDIForm.frmViewTicketsActive==false){
            frmViewTickets vt = new frmViewTickets();
            MDIForm.DesktopPane.add(vt);
            int height = MDIForm.DesktopPane.getHeight();
            int width = MDIForm.DesktopPane.getWidth();
            int x = (int)(height-vt.getHeight())/2;
            int y = (int)(width-vt.getWidth())/2;
            vt.setLocation(y,x);
            vt.setVisible(true);
        }   
    }//GEN-LAST:event_btnCancelTicketsActionPerformed

    private void btnAddNewCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCustActionPerformed
        
        if(MDIForm.frmViewTicketsActive==false){
            frmNewCust ncust = new frmNewCust();
            MDIForm.DesktopPane.add(ncust);
            int height = MDIForm.DesktopPane.getHeight();
            int width = MDIForm.DesktopPane.getWidth();
            int x = (int)(height-ncust.getHeight())/2;
            int y = (int)(width-ncust.getWidth())/2;
            ncust.setLocation(y,x);
            ncust.setVisible(true);
        }
    }//GEN-LAST:event_btnAddNewCustActionPerformed

    private void btnViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerActionPerformed
        frmViewCust frmview = new frmViewCust();
        MDIForm.DesktopPane.add(frmview);
        int height = MDIForm.DesktopPane.getHeight();
        int width = MDIForm.DesktopPane.getWidth();
        int x = (int)(height-frmview.getHeight())/2;
        int y = (int)(width-frmview.getWidth())/2;
        frmview.setLocation(y,x);
        frmview.setVisible(true);
        
        
    }//GEN-LAST:event_btnViewCustomerActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked

            int userChoice = JOptionPane.showConfirmDialog(null,"Do you want to logout?", "Logout Confirm", JOptionPane.YES_NO_OPTION);
            if(userChoice==0){
                MDIForm.loggedin=false;
                MDIForm.loggedUserID="";
                MDIForm.loggedUserAccess="";
                MDIForm.DesktopPane.removeAll();
                MDIForm.DesktopPane.repaint();
                frmSignin s =new frmSignin();
                MDIForm.DesktopPane.add(s);
                int height = MDIForm.DesktopPane.getHeight();
                int width = MDIForm.DesktopPane.getWidth();
                int x = (int)(height-s.getHeight())/2;
                int y = (int)(width-s.getWidth())/2;
                s.setLocation(y,x);
                s.setVisible(true);            
            }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblrecipIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrecipIDMouseClicked
        frmViewAccRecip frmacc = new frmViewAccRecip();
        MDIForm.DesktopPane.add(frmacc);
        int height = MDIForm.DesktopPane.getHeight();
        int width = MDIForm.DesktopPane.getWidth();
        int x = (int)(height-frmacc.getHeight())/2;
        int y = (int)(width-frmacc.getWidth())/2;
        frmacc.setLocation(y,x);
        frmacc.setVisible(true);
    }//GEN-LAST:event_lblrecipIDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCust;
    private javax.swing.JButton btnCancelTickets;
    private javax.swing.JButton btnReserveTickets;
    private javax.swing.JButton btnViewCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblRecipName;
    private javax.swing.JLabel lblrecipID;
    private javax.swing.JTable tblFlights;
    // End of variables declaration//GEN-END:variables
}
