/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AirTicketReservationSystem;

import javax.swing.*;
import java.sql.*;
import javax.swing.JOptionPane;

public class frmSignin extends javax.swing.JInternalFrame {

    Connection dbcon;
    
    public frmSignin() {
        
        initComponents();
        dbcon = dbConnectr.Connect();
        SwingUtilities.getRootPane(btnsignin).setDefaultButton(btnsignin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpaccessType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        btnsignin = new javax.swing.JButton();

        setClosable(true);
        setTitle("Sign In");
        setPreferredSize(new java.awt.Dimension(312, 225));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Username :");

        jLabel2.setText("Password :");

        btnsignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconSignin.png"))); // NOI18N
        btnsignin.setText("Sign In");
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsignin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtusername)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnsignin)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setBounds(0, 0, 327, 207);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed

        String UserID;
        String username = txtusername.getText();
        String password = txtpassword.getText();
        
        boolean unOK = false;
        boolean pwOK = false;
        boolean accessOK = false;
        String SQL = "select * from logininfo";
        
        if(username.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(this,"Fill the details!","Signin failed!",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                Statement  stmnt = dbcon.createStatement();
                ResultSet rslogininfo = stmnt.executeQuery(SQL);

                while(rslogininfo.next()){

                        if(username.equals(rslogininfo.getString("userName"))){
                            unOK = true;
                            if(password.equals(rslogininfo.getString("password"))){
                                pwOK = true;
                                MDIForm.loggedUserID=rslogininfo.getString("userID");
                                MDIForm.loggedUserAccess = rslogininfo.getString("accessType");
                            }
                        }
                }

                if(unOK && pwOK){
                    MDIForm.loggedin = true;
                    if(MDIForm.loggedUserAccess.equals("recip")){
                        frmRecipMain nrecip =new frmRecipMain();
                        MDIForm.DesktopPane.add(nrecip);
                        int height = MDIForm.DesktopPane.getHeight();
                        int width = MDIForm.DesktopPane.getWidth();
                        int x = (int)(height-nrecip.getHeight())/2;
                        int y = (int)(width-nrecip.getWidth())/2;
                        nrecip.setLocation(y,x);
                        try {
                            this.setClosed(true);
                        } 
                        catch(Exception ex) {
                            JOptionPane.showMessageDialog(null, "Something happened.","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        nrecip.setVisible(true);
                    }
                    else if(MDIForm.loggedUserAccess.equals("admin")){
                        frmAdminMain adm =new frmAdminMain();
                        MDIForm.DesktopPane.add(adm);
                        int height = MDIForm.DesktopPane.getHeight();
                        int width = MDIForm.DesktopPane.getWidth();
                        int x = (int)(height-adm.getHeight())/2;
                        int y = (int)(width-adm.getWidth())/2;
                        adm.setLocation(y,x);
                        try {
                            this.setClosed(true);
                        } 
                        catch(Exception ex) {
                            JOptionPane.showMessageDialog(null, "Something happened.","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        adm.setVisible(true);
                    }
                }
                else if(unOK){
                    JOptionPane.showMessageDialog(null, "Invalid Password","Signin failed!",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid User Account","Signin failed!",JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(Exception exc){
                JOptionPane.showMessageDialog(null, "Something happened.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnsigninActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        MDIForm.frmSigninActive = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        MDIForm.frmSigninActive = true;
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsignin;
    private javax.swing.ButtonGroup grpaccessType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
