/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AirTicketReservationSystem;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class frmViewCust extends javax.swing.JInternalFrame {

    Connection dbcon = null;
    
    public frmViewCust() {
        initComponents();
        dbcon = dbConnectr.Connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtLname = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblFname = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        eiFname = new javax.swing.JLabel();
        eiLname = new javax.swing.JLabel();
        eiNIC = new javax.swing.JLabel();
        eiAddress = new javax.swing.JLabel();
        eiFname1 = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        lblCustId = new javax.swing.JLabel();
        lblPassport = new javax.swing.JLabel();
        txtPassport = new javax.swing.JTextField();
        eiPassport = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtDOB = new com.toedter.calendar.JDateChooser();
        lblDOB = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        lblGender = new javax.swing.JLabel();
        radioFemale = new javax.swing.JRadioButton();
        lblContactNo = new javax.swing.JLabel();
        txtContactno = new javax.swing.JTextField();
        eiDOB = new javax.swing.JLabel();
        eiGender = new javax.swing.JLabel();
        eiContactno = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        eiCity = new javax.swing.JLabel();
        eiEmail = new javax.swing.JLabel();
        btnSaveCustomer = new javax.swing.JButton();
        btnEditDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        profilePic = new javax.swing.JPanel();
        lblProfPic = new javax.swing.JLabel();
        btnRemoveImage = new javax.swing.JButton();
        btnAddImage = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtSearchCust = new javax.swing.JTextField();
        combSearchType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setClosable(true);
        setTitle("View Customer");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        txtLname.setToolTipText("(Maximum 20 Characters)");

        lblLname.setText("Last Name :");

        txtFname.setToolTipText("(Maximum 20 Characters)");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        lblFname.setText("First Name :");

        lblAddress.setText("Address :");

        lblNIC.setText("NIC No :");

        txtNIC.setToolTipText("(eg : 123456789v)");

        eiFname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        eiLname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        eiNIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        eiAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        eiFname1.setText("              ");

        lblCustomerID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCustomerID.setText("Customer ID :");

        lblCustId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCustId.setText("No Customer");

        lblPassport.setText("Passport ID :");

        txtPassport.setToolTipText("(Maximum 10 Digits)");

        eiPassport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        txtDOB.setToolTipText("");
        txtDOB.setDateFormatString("d-MM-yyyy");

        lblDOB.setText("Date of Birth :");

        btngrpGender.add(radioMale);
        radioMale.setText("Male");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });

        lblGender.setText("Gender :");

        btngrpGender.add(radioFemale);
        radioFemale.setText("Female");
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });

        lblContactNo.setText("Contact No :");

        txtContactno.setToolTipText("(eg : 0123456789)");

        eiDOB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        eiGender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        eiContactno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        lblCity.setText("City :");

        lblEmail.setText("E - mail :");

        txtEmail.setToolTipText("(eg : name@example.com)");

        eiCity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        eiEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/error.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDOB)
                    .addComponent(lblGender)
                    .addComponent(lblContactNo)
                    .addComponent(lblCity)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eiCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eiEmail, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtContactno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eiContactno))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(radioMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioFemale)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eiGender)
                            .addComponent(eiDOB))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblDOB))
                    .addComponent(eiDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioMale)
                        .addComponent(radioFemale)
                        .addComponent(lblGender))
                    .addComponent(eiGender))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblContactNo)
                        .addComponent(txtContactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eiContactno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eiEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eiCity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCity)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCustomerID)
                        .addGap(18, 18, 18)
                        .addComponent(lblCustId, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eiFname1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblLname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNIC)
                                    .addComponent(lblPassport))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNIC)
                                    .addComponent(txtPassport, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eiFname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eiLname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eiNIC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eiAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eiPassport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eiFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerID)
                            .addComponent(lblCustId))
                        .addGap(27, 27, 27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFname)
                                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eiFname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eiLname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLname)
                                .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNIC))
                            .addComponent(eiNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPassport))
                            .addComponent(eiPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(eiAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblAddress))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSaveCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconAddUser24x.png"))); // NOI18N
        btnSaveCustomer.setText("Save Changes");
        btnSaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCustomerActionPerformed(evt);
            }
        });

        btnEditDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconEdit.png"))); // NOI18N
        btnEditDetails.setText("Edit Details");
        btnEditDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDetailsActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconRemoveUser24x.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        profilePic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProfPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/ppicon.png"))); // NOI18N

        javax.swing.GroupLayout profilePicLayout = new javax.swing.GroupLayout(profilePic);
        profilePic.setLayout(profilePicLayout);
        profilePicLayout.setHorizontalGroup(
            profilePicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfPic, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profilePicLayout.setVerticalGroup(
            profilePicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfPic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRemoveImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconRemoveImage.png"))); // NOI18N
        btnRemoveImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveImageActionPerformed(evt);
            }
        });

        btnAddImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconAddImage.png"))); // NOI18N
        btnAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnAddImage, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveImage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddImage)
                    .addComponent(btnRemoveImage))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveCustomer)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveCustomer)
                    .addComponent(btnEditDetails)
                    .addComponent(btnDelete))
                .addGap(21, 21, 21))
        );

        combSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer ID", "Passport No", "NIC No" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Search :");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketReservationSystem/IconSearch.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSearchCust, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnSearch))
                    .addComponent(combSearchType, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchCust, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        MDIForm.frmViewCustActive = true;
        eiFname.setVisible(false);
        eiLname.setVisible(false);
        eiNIC.setVisible(false);
        eiPassport.setVisible(false);
        eiAddress.setVisible(false);
        eiCity.setVisible(false);
        eiDOB.setVisible(false);
        eiGender.setVisible(false);
        eiEmail.setVisible(false);
        eiContactno.setVisible(false);
        this.txtFname.setEnabled(false);
        this.txtLname.setEnabled(false);
        this.txtNIC.setEnabled(false);
        this.txtPassport.setEnabled(false);
        this.txtAddress.setEnabled(false);
        this.txtCity.setEnabled(false);
        this.txtDOB.setEnabled(false);
        this.txtContactno.setEnabled(false);
        this.txtEmail.setEnabled(false);
        this.btnDelete.setEnabled(false);
        this.btnAddImage.setEnabled(false);
        this.btnRemoveImage.setEnabled(false);
        this.btnSaveCustomer.setEnabled(false);
        this.btnEditDetails.setEnabled(false);
        this.radioFemale.setEnabled(false);
        this.radioMale.setEnabled(false);
        this.lblCustomerID.setEnabled(false);
        this.lblCustId.setEnabled(false);
        this.lblFname.setEnabled(false);
        this.lblLname.setEnabled(false);
        this.lblNIC.setEnabled(false);
        this.lblPassport.setEnabled(false);
        this.lblAddress.setEnabled(false);
        this.lblDOB.setEnabled(false);
        this.lblGender.setEnabled(false);
        this.lblCity.setEnabled(false);
        this.lblContactNo.setEnabled(false);
        this.lblEmail.setEnabled(false);
        this.txtFname.setEditable(false);
        this.txtLname.setEditable(false);
        this.txtNIC.setEditable(false);
        this.txtPassport.setEditable(false);
        this.txtAddress.setEditable(false);
        this.txtCity.setEditable(false);
        this.txtContactno.setEditable(false);
        this.txtEmail.setEditable(false);
        this.defprofimg = this.lblProfPic.getIcon();
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        MDIForm.frmViewCustActive = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed

    }//GEN-LAST:event_radioMaleActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed

    }//GEN-LAST:event_radioFemaleActionPerformed

    private void btnSaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCustomerActionPerformed
        if(checkEntryDetails()){
            int userChoice = JOptionPane.showConfirmDialog(null,"Are you sure details are correct?", "Confirm Details", JOptionPane.YES_NO_OPTION);
            
            if(userChoice==0){
                String update_cust_info_SQL = "update cust_info set fname=?,lname=?,address=?,gender=?,dob=?,nic=?,passport=?,city=?,email=?,contact=?,profimg=? where custID=?";
                try{
                    PreparedStatement pst = dbcon.prepareStatement(update_cust_info_SQL);
                    
                    pst.setString(1, this.txtFname.getText());
                    pst.setString(2, this.txtLname.getText());
                    pst.setString(3, this.txtAddress.getText());
                    pst.setString(4, this.btngrpGender.getSelection().getActionCommand());
                    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                    String dob = df.format(txtDOB.getDate());
                    pst.setString(5, dob);
                    pst.setString(6, this.txtNIC.getText());
                    pst.setString(7, this.txtPassport.getText());
                    pst.setString(8, this.txtCity.getText());
                    pst.setString(9, this.txtEmail.getText());
                    pst.setString(10, this.txtContactno.getText());
                    pst.setBytes(11, prof_img);
                    pst.setString(12, this.lblCustId.getText());
                    pst.executeUpdate();
                    //-----------------------------------------------------
                    this.txtFname.setEditable(false);
                    this.txtLname.setEditable(false);
                    this.txtNIC.setEditable(false);
                    this.txtPassport.setEditable(false);
                    this.txtAddress.setEditable(false);
                    this.txtCity.setEditable(false);
                    this.txtDOB.setEnabled(false);
                    this.txtContactno.setEditable(false);
                    this.txtEmail.setEditable(false);
                    this.btnAddImage.setEnabled(false);
                    this.btnRemoveImage.setEnabled(false);
                    this.btnSaveCustomer.setEnabled(false);
                    if(radioFemale.isSelected()){
                        this.radioFemale.setEnabled(true);
                        this.radioMale.setEnabled(false);
                    }
                    else{
                        this.radioFemale.setEnabled(false);
                        this.radioMale.setEnabled(true);
                    }
                    //-----------------------------------------------------
                    JOptionPane.showMessageDialog(null, "Customer "+this.lblCustId.getText()+" was successfully Updated.", "Updating Customer Complete", JOptionPane.INFORMATION_MESSAGE);
                }
                catch(Exception exc){
                    JOptionPane.showMessageDialog(null, "Database connection omg failed while saving information","Database Connection Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Fill all the details correctly", "Adding Details Failed!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveCustomerActionPerformed

    private void btnAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImageActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","png","jpg");  
        jfc.addChoosableFileFilter(filter);
        jfc.setDialogTitle("Select an image");
        int result = jfc.showOpenDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            File imgfile = jfc.getSelectedFile();
            imgpath = imgfile.getAbsolutePath();
            this.lblProfPic.setIcon(getImage(imgpath));
            try{
                File image = new File(imgpath);
                FileInputStream fis = new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[1024];
                for(int readNum; (readNum=fis.read(buf))!=-1;){
                    bos.write(buf,0,readNum);
                }
                prof_img = bos.toByteArray();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        } 
        
    }//GEN-LAST:event_btnAddImageActionPerformed

    private void btnRemoveImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveImageActionPerformed
        prof_img = null;
        this.lblProfPic.setIcon(this.defprofimg);
        
    }//GEN-LAST:event_btnRemoveImageActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        eiFname.setVisible(false);
        eiLname.setVisible(false);
        eiNIC.setVisible(false);
        eiAddress.setVisible(false);
        eiCity.setVisible(false);
        eiDOB.setVisible(false);
        eiGender.setVisible(false);
        eiEmail.setVisible(false);
        eiContactno.setVisible(false);
        this.txtFname.setEnabled(false);
        this.txtLname.setEnabled(false);
        this.txtNIC.setEnabled(false);
        this.txtPassport.setEnabled(false);
        this.txtAddress.setEnabled(false);
        this.txtCity.setEnabled(false);
        this.txtDOB.setEnabled(false);
        this.txtContactno.setEnabled(false);
        this.txtEmail.setEnabled(false);
        this.btnAddImage.setEnabled(false);
        this.btnRemoveImage.setEnabled(false);
        this.btnSaveCustomer.setEnabled(false);
        this.btnEditDetails.setEnabled(false);
        this.btnDelete.setEnabled(false);
        this.radioFemale.setEnabled(false);
        this.radioMale.setEnabled(false);
        this.txtFname.setEditable(false);
        this.txtLname.setEditable(false);
        this.txtNIC.setEditable(false);
        this.txtAddress.setEditable(false);
        this.txtCity.setEditable(false);
        this.txtContactno.setEditable(false);
        this.txtEmail.setEditable(false);
        this.lblProfPic.setIcon(defprofimg);
        this.lblCustomerID.setEnabled(false);
        this.lblCustId.setEnabled(false);
        this.lblFname.setEnabled(false);
        this.lblLname.setEnabled(false);
        this.lblNIC.setEnabled(false);
        this.lblPassport.setEnabled(false);
        this.lblAddress.setEnabled(false);
        this.lblDOB.setEnabled(false);
        this.lblGender.setEnabled(false);
        this.lblCity.setEnabled(false);
        this.lblContactNo.setEnabled(false);
        this.lblEmail.setEnabled(false);
        
        if(this.txtSearchCust.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty Search Field","Search Error",JOptionPane.ERROR_MESSAGE);            
        }
        else{
            if(this.combSearchType.getSelectedItem().toString().equals("Customer ID")){
                boolean found=false;
                try{
                    String SQL = "select custID from cust_info where custID='"+this.txtSearchCust.getText()+"'";
                    Statement stmnt = dbcon.createStatement();
                    ResultSet rs = stmnt.executeQuery(SQL);
                    while(rs.next()){
                        if(rs.getString("custID").equals(this.txtSearchCust.getText())){
                            found=true;
                        }
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Database communication error","Database Error",JOptionPane.ERROR_MESSAGE);  
                }
                //--------------------------------------------------------------------------------------
                if(found){
                    JOptionPane.showMessageDialog(null, "Match found","Search Success",JOptionPane.INFORMATION_MESSAGE);
                    getCustDetails_custID(this.txtSearchCust.getText());
                    if(MDIForm.loggedUserAccess.equals("admin")){
                        this.btnDelete.setEnabled(true);
                    }
                    else{
                        this.btnDelete.setEnabled(false);
                    }
                    this.lblCustomerID.setEnabled(true);
                    this.lblCustId.setEnabled(true);
                    this.lblFname.setEnabled(true);
                    this.lblLname.setEnabled(true);
                    this.lblNIC.setEnabled(true);
                    this.lblPassport.setEnabled(true);
                    this.lblAddress.setEnabled(true);
                    this.lblDOB.setEnabled(true);
                    this.lblGender.setEnabled(true);
                    this.lblCity.setEnabled(true);
                    this.lblContactNo.setEnabled(true);
                    this.lblEmail.setEnabled(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "No match found","Search Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(this.combSearchType.getSelectedItem().toString().equals("Passport No")){
                boolean found=false;
                try{
                    String SQL = "select passport from cust_info where passport='"+this.txtSearchCust.getText()+"'";
                    Statement stmnt = dbcon.createStatement();
                    ResultSet rs = stmnt.executeQuery(SQL);
                    while(rs.next()){
                        if(rs.getString("passport").equals(this.txtSearchCust.getText())){
                            found=true;
                        }
                    }
                }
                catch(Exception e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Database communication error","Database Error",JOptionPane.ERROR_MESSAGE);  
                }
                //--------------------------------------------------------------------------------------
                if(found){
                    JOptionPane.showMessageDialog(null, "Match found","Search Success",JOptionPane.INFORMATION_MESSAGE);
                    getCustDetails_Passport(this.txtSearchCust.getText());
                    if(MDIForm.loggedUserAccess.equals("admin")){
                        this.btnDelete.setEnabled(true);
                    }
                    else{
                        this.btnDelete.setEnabled(false);
                    }
                    this.lblCustomerID.setEnabled(true);
                    this.lblCustId.setEnabled(true);
                    this.lblFname.setEnabled(true);
                    this.lblLname.setEnabled(true);
                    this.lblNIC.setEnabled(true);
                    this.lblPassport.setEnabled(true);
                    this.lblAddress.setEnabled(true);
                    this.lblDOB.setEnabled(true);
                    this.lblGender.setEnabled(true);
                    this.lblCity.setEnabled(true);
                    this.lblContactNo.setEnabled(true);
                    this.lblEmail.setEnabled(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "No match found","Search Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(this.combSearchType.getSelectedItem().toString().equals("NIC No")){
                boolean found=false;
                try{
                    String SQL = "select nic from cust_info where nic='"+this.txtSearchCust.getText()+"'";
                    Statement stmnt = dbcon.createStatement();
                    ResultSet rs = stmnt.executeQuery(SQL);
                    while(rs.next()){
                        if(rs.getString("nic").equals(this.txtSearchCust.getText())){
                            found=true;
                        }
                    }
                }
                catch(Exception e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Database communication error","Database Error",JOptionPane.ERROR_MESSAGE);  
                }
                //--------------------------------------------------------------------------------------
                if(found){
                    JOptionPane.showMessageDialog(null, "Match found","Search Success",JOptionPane.INFORMATION_MESSAGE);
                    getCustDetails_NIC(this.txtSearchCust.getText());
                    if(MDIForm.loggedUserAccess.equals("admin")){
                        this.btnDelete.setEnabled(true);
                    }
                    else{
                        this.btnDelete.setEnabled(false);
                    }
                    this.lblCustomerID.setEnabled(true);
                    this.lblCustId.setEnabled(true);
                    this.lblFname.setEnabled(true);
                    this.lblLname.setEnabled(true);
                    this.lblNIC.setEnabled(true);
                    this.lblPassport.setEnabled(true);
                    this.lblAddress.setEnabled(true);
                    this.lblDOB.setEnabled(true);
                    this.lblGender.setEnabled(true);
                    this.lblCity.setEnabled(true);
                    this.lblContactNo.setEnabled(true);
                    this.lblEmail.setEnabled(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "No match found","Search Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDetailsActionPerformed
        this.txtFname.setEditable(true);
        this.txtLname.setEditable(true);
        this.txtNIC.setEditable(true);
        this.txtPassport.setEditable(true);
        this.txtAddress.setEditable(true);
        this.txtCity.setEditable(true);
        this.txtDOB.setEnabled(true);
        this.txtContactno.setEditable(true);
        this.txtEmail.setEditable(true);
        this.btnAddImage.setEnabled(true);
        this.btnRemoveImage.setEnabled(true);
        this.btnSaveCustomer.setEnabled(true);
        this.radioFemale.setEnabled(true);
        this.radioMale.setEnabled(true);
    }//GEN-LAST:event_btnEditDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int userChoice = JOptionPane.showConfirmDialog(null,"Are you sure to delete this account?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        
        if(userChoice==0){
            String SQL = "delete from cust_info where custID='"+this.lblCustId.getText()+"'";
            try{
                Statement stmnt = dbcon.createStatement();
                stmnt.executeUpdate(SQL);
                JOptionPane.showMessageDialog(null, "Customer "+this.lblCustId.getText()+" deleted successfully", "Delete Successful!", JOptionPane.INFORMATION_MESSAGE);
                //-----------------
                    this.setClosed(true);
                    frmViewCust frmcust = new frmViewCust();
                    MDIForm.DesktopPane.add(frmcust);
                    int height = MDIForm.DesktopPane.getHeight();
                    int width = MDIForm.DesktopPane.getWidth();
                    int x = (int)(height-frmcust.getHeight())/2;
                    int y = (int)(width-frmcust.getWidth())/2;
                    frmcust.setLocation(y,x);
                    frmcust.setVisible(true);
                //-----------------
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Cannot Delete Customer", "Database Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    public ImageIcon getImage(String path){
        ImageIcon ProfImg = new ImageIcon(path);
        Image img = ProfImg.getImage();
        Image newImg = img.getScaledInstance(lblProfPic.getWidth(), lblProfPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage = new ImageIcon(newImg);
        return finalImage;
    }
    
    public void getCustDetails_custID(String custid){
        //Enable items
        this.txtFname.setEnabled(true);
        this.txtLname.setEnabled(true);
        this.txtNIC.setEnabled(true);
        this.txtPassport.setEnabled(true);
        this.txtAddress.setEnabled(true);
        this.txtCity.setEnabled(true);
        this.txtDOB.setEnabled(false);
        this.txtContactno.setEnabled(true);
        this.txtEmail.setEnabled(true);
        this.btnAddImage.setEnabled(false);
        this.btnRemoveImage.setEnabled(false);
        this.btnSaveCustomer.setEnabled(false);
        this.btnEditDetails.setEnabled(true);
        this.radioFemale.setEnabled(false);
        this.radioMale.setEnabled(false);
        //------------------------------------------------------
        this.lblCustId.setText(custid);
        
        try{
            String SQL = "select * from cust_info where custID = ?"; 
            PreparedStatement pst = dbcon.prepareStatement(SQL);
            pst.setString(1, custid);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                this.txtFname.setText(rs.getString("fname"));
                this.txtLname.setText(rs.getString("lname"));
                this.txtNIC.setText(rs.getString("nic"));
                this.txtPassport.setText(rs.getString("passport"));
                this.txtAddress.setText(rs.getString("address"));
                this.txtCity.setText(rs.getString("city"));
                this.txtContactno.setText(rs.getString("contact"));
                this.txtEmail.setText(rs.getString("email"));
                if(rs.getString("gender").equals("Male")){
                    this.radioMale.setEnabled(true);
                    this.radioMale.setSelected(true);
                }
                else{
                    this.radioFemale.setSelected(true);
                    this.radioFemale.setEnabled(true);
                }
                //setdate
                String datevalue = rs.getString("dob");
                try{
                    Date date = new SimpleDateFormat("yyyy-MM-dd").parse(datevalue);
                    this.txtDOB.setDate(date);
                }
                catch(Exception e){
                    e.printStackTrace();
                }
                //end setdate
                //set profpic
                if(rs.getBytes("profimg")!=null){
                    byte[] imagedata = rs.getBytes("profimg");
                    this.prof_img = rs.getBytes("profimg"); // current database profile image
                    ImageIcon img = new ImageIcon(imagedata);
                    Image resizedimage = img.getImage().getScaledInstance(lblProfPic.getWidth(), lblProfPic.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon finalImage = new ImageIcon(resizedimage);
                    this.lblProfPic.setIcon(finalImage);
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
    public void getCustDetails_NIC(String nic){
        //Enable items
        this.txtFname.setEnabled(true);
        this.txtLname.setEnabled(true);
        this.txtNIC.setEnabled(true);
        this.txtPassport.setEnabled(true);
        this.txtAddress.setEnabled(true);
        this.txtCity.setEnabled(true);
        this.txtDOB.setEnabled(false);
        this.txtContactno.setEnabled(true);
        this.txtEmail.setEnabled(true);
        this.btnAddImage.setEnabled(false);
        this.btnRemoveImage.setEnabled(false);
        this.btnSaveCustomer.setEnabled(false);
        this.btnEditDetails.setEnabled(true);
        this.radioFemale.setEnabled(false);
        this.radioMale.setEnabled(false);
        //------------------------------------------------------
        
        try{
            String SQL = "select * from cust_info where nic = ?"; 
            PreparedStatement pst = dbcon.prepareStatement(SQL);
            pst.setString(1, nic);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                this.lblCustId.setText(rs.getString("custID"));
                this.txtFname.setText(rs.getString("fname"));
                this.txtLname.setText(rs.getString("lname"));
                this.txtNIC.setText(rs.getString("nic"));
                this.txtPassport.setText(rs.getString("passport"));
                this.txtAddress.setText(rs.getString("address"));
                this.txtCity.setText(rs.getString("city"));
                this.txtContactno.setText(rs.getString("contact"));
                this.txtEmail.setText(rs.getString("email"));
                if(rs.getString("gender").equals("Male")){
                    this.radioMale.setEnabled(true);
                    this.radioMale.setSelected(true);
                }
                else{
                    this.radioFemale.setSelected(true);
                    this.radioFemale.setEnabled(true);
                }
                //setdate
                String datevalue = rs.getString("dob");
                try{
                    Date date = new SimpleDateFormat("yyyy-MM-dd").parse(datevalue);
                    this.txtDOB.setDate(date);
                }
                catch(Exception e){
                    e.printStackTrace();
                }
                //end setdate
                //set profpic
                if(rs.getBytes("profimg")!=null){
                    byte[] imagedata = rs.getBytes("profimg");
                    this.prof_img = rs.getBytes("profimg"); // current database profile image
                    ImageIcon img = new ImageIcon(imagedata);
                    Image resizedimage = img.getImage().getScaledInstance(lblProfPic.getWidth(), lblProfPic.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon finalImage = new ImageIcon(resizedimage);
                    this.lblProfPic.setIcon(finalImage);
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void getCustDetails_Passport(String passport){
        //Enable items
        this.txtFname.setEnabled(true);
        this.txtLname.setEnabled(true);
        this.txtNIC.setEnabled(true);
        this.txtPassport.setEnabled(true);
        this.txtAddress.setEnabled(true);
        this.txtCity.setEnabled(true);
        this.txtDOB.setEnabled(false);
        this.txtContactno.setEnabled(true);
        this.txtEmail.setEnabled(true);
        this.btnAddImage.setEnabled(false);
        this.btnRemoveImage.setEnabled(false);
        this.btnSaveCustomer.setEnabled(false);
        this.btnEditDetails.setEnabled(true);
        this.radioFemale.setEnabled(false);
        this.radioMale.setEnabled(false);
        //------------------------------------------------------
        
        try{
            String SQL = "select * from cust_info where passport = ?"; 
            PreparedStatement pst = dbcon.prepareStatement(SQL);
            pst.setString(1, passport);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                this.lblCustId.setText(rs.getString("custID"));
                this.txtFname.setText(rs.getString("fname"));
                this.txtLname.setText(rs.getString("lname"));
                this.txtNIC.setText(rs.getString("nic"));
                this.txtPassport.setText(rs.getString("passport"));
                this.txtAddress.setText(rs.getString("address"));
                this.txtCity.setText(rs.getString("city"));
                this.txtContactno.setText(rs.getString("contact"));
                this.txtEmail.setText(rs.getString("email"));
                if(rs.getString("gender").equals("Male")){
                    this.radioMale.setEnabled(true);
                    this.radioMale.setSelected(true);
                }
                else{
                    this.radioFemale.setSelected(true);
                    this.radioFemale.setEnabled(true);
                }
                //setdate
                String datevalue = rs.getString("dob");
                try{
                    Date date = new SimpleDateFormat("yyyy-MM-dd").parse(datevalue);
                    this.txtDOB.setDate(date);
                }
                catch(Exception e){
                    e.printStackTrace();
                }
                //end setdate
                //set profpic
                if(rs.getBytes("profimg")!=null){
                    byte[] imagedata = rs.getBytes("profimg");
                    this.prof_img = rs.getBytes("profimg"); // current database profile image
                    ImageIcon img = new ImageIcon(imagedata);
                    Image resizedimage = img.getImage().getScaledInstance(lblProfPic.getWidth(), lblProfPic.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon finalImage = new ImageIcon(resizedimage);
                    this.lblProfPic.setIcon(finalImage);
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void increaseCustByOne(){
        String SQL = "select Cust from usercount";
        int nCust=0;
        try{
            Statement stmnt = dbcon.createStatement();
            ResultSet rs = stmnt.executeQuery(SQL);
            while(rs.next()){
            nCust = rs.getInt("Cust");
            }
            
            String SQL2 = "update usercount set Cust="+(nCust+1)+" where Cust="+nCust;
            System.out.println(SQL2);
            
            try{
                Statement stmnt2 = dbcon.createStatement();
                stmnt.executeUpdate(SQL2);
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Database connection failed while saving information","Database Connection Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Database connection failed while saving information","Database Connection Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public String generateUserID(String accType){
        String SQL = "select * from usercount";
        String aType="";
        int nUsers=0;
        String UserID="";
        
        try{
            Statement stmnt = dbcon.createStatement();
            
            ResultSet rs = stmnt.executeQuery(SQL);
            while(rs.next()){
                if(accType=="MAdmin"){
                    aType="A";
                    nUsers = rs.getInt("Admin");
                }
                else if(accType=="Admin"){
                    aType="A";
                    nUsers = rs.getInt("Admin");
                }
                else if(accType=="Recip"){
                    aType="R";
                    nUsers = rs.getInt("Recip");
                }
                else if(accType=="Cust"){
                    aType="C";
                    nUsers = rs.getInt("Cust");
                }
            } 
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(null, "Database connection failed while generating userID","Database Connection Error",JOptionPane.ERROR_MESSAGE);
        }
        
        if(nUsers<9){
            UserID=aType.concat("000").concat(Integer.toString(nUsers+1));
        }
        else if(nUsers<99){
            UserID=aType.concat("00").concat(Integer.toString(nUsers+1));
        }
        else if(nUsers<999){
            UserID=aType.concat("0").concat(Integer.toString(nUsers+1));
        }
        else if(nUsers<9999){
            UserID=aType.concat(Integer.toString(nUsers+1));
        }
        else{
            JOptionPane.showMessageDialog(null, "Cannot Generate UserID. Maximum Users Reached","Error",JOptionPane.ERROR_MESSAGE);
        }
        return UserID;
    }
    
    public boolean cktxtFname(){
        if(txtFname.getText().equals("")){
            eiFname.setVisible(true);
            eiFname.setToolTipText("Empty Field!");
            return false;
        }
        else{
            if(txtFname.getText().length()>20){
                eiFname.setVisible(true);
                eiFname.setToolTipText("Maximum characters exceed!");
                return false;
            }
            else{
                eiFname.setVisible(false);
                return true;
            }
        }
    }
    
    public boolean cktxtLname(){
        if(txtLname.getText().equals("")){
            eiLname.setVisible(true);
            eiLname.setToolTipText("Empty Field!");
            return false;
        }
        else{
            if(txtLname.getText().length()>20){
                eiLname.setVisible(true);
                eiLname.setToolTipText("Maximum characters exceed!");
                return false;
            }
            else{
                eiLname.setVisible(false);
                return true;
            }
        }
    }
    
    public boolean cktxtNIC(){
                
        if(txtNIC.getText().equals("")){
            eiNIC.setVisible(true);
            eiNIC.setToolTipText("Empty Field!");
            return false;
        }
        else{
            if(txtNIC.getText().length()==10){
                String NIC = txtNIC.getText();
                if(Character.isDigit(NIC.charAt(0))==false){
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
                else if(Character.isDigit(NIC.charAt(1))==false){
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
                else if(Character.isDigit(NIC.charAt(2))==false){
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
                else if(Character.isDigit(NIC.charAt(3))==false){
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
                else if(Character.isDigit(NIC.charAt(4))==false){
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
                else if(Character.isDigit(NIC.charAt(5))==false){
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
                else if(Character.isDigit(NIC.charAt(6))==false){
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
                else if(Character.isDigit(NIC.charAt(7))==false){
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
                else if(Character.isDigit(NIC.charAt(8))==false){
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
                else if(NIC.charAt(9)=='v' || NIC.charAt(9)=='V'){
                    boolean nicavailable=false;
                    String custidofnic="";
                    String SQL = "select custID, nic from cust_info";
                    try{
                        Statement stmnt = dbcon.createStatement();
                        ResultSet rs = stmnt.executeQuery(SQL);
                        
                        while(rs.next()){
                            if(rs.getString("nic").equalsIgnoreCase(NIC)){
                                nicavailable=true;
                                custidofnic = rs.getString("custID");
                                break;
                            }
                        }
                    }
                    catch(Exception e){
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Communicating with database failed", "Check NIC Failed!", JOptionPane.ERROR_MESSAGE);

                    }
                    if(nicavailable==true && custidofnic.equals(this.lblCustId.getText())){
                        eiNIC.setVisible(false);
                        return true;
                    }
                    else if(nicavailable==true && custidofnic.equals(this.lblCustId.getText())==false){
                        eiNIC.setVisible(true);
                        eiNIC.setToolTipText("This NIC already exists!");
                        return false;
                    }
                    else if(nicavailable==false){
                        eiNIC.setVisible(false);
                        return true;
                    }
                    else{
                        eiNIC.setVisible(true);
                        eiNIC.setToolTipText("This NIC already exists!");
                        return false;
                    }
                }
                else{
                    eiNIC.setVisible(true);
                    eiNIC.setToolTipText("Invalid NIC!");
                    return false;
                }
            }
            else{
                eiNIC.setVisible(true);
                eiNIC.setToolTipText("Invalid NIC!");
                return false;
            }
        }
    }
    
    public boolean cktxtPassport(){
                
        if(txtPassport.getText().equals("")){
            eiPassport.setVisible(true);
            eiPassport.setToolTipText("Empty Field!");
            return false;
        }
        else{
            if(txtPassport.getText().length()==10){
                String Passport = txtPassport.getText();
                if(Character.isDigit(Passport.charAt(0))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else if(Character.isDigit(Passport.charAt(1))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else if(Character.isDigit(Passport.charAt(2))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else if(Character.isDigit(Passport.charAt(3))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else if(Character.isDigit(Passport.charAt(4))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else if(Character.isDigit(Passport.charAt(5))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else if(Character.isDigit(Passport.charAt(6))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else if(Character.isDigit(Passport.charAt(7))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else if(Character.isDigit(Passport.charAt(8))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else if(Character.isDigit(Passport.charAt(9))==false){
                    eiPassport.setVisible(true);
                    eiPassport.setToolTipText("Invalid Passport!");
                    return false;
                }
                else{
                    boolean Passportavailable=false;
                    String custidofPassport="";
                    String SQL = "select custID, passport from cust_info";
                    try{
                        Statement stmnt = dbcon.createStatement();
                        ResultSet rs = stmnt.executeQuery(SQL);
                        
                        while(rs.next()){
                            if(rs.getString("passport").equals(Passport)){
                                Passportavailable=true;
                                custidofPassport = rs.getString("custID");
                                break;
                            }
                        }
                    }
                    catch(Exception e){
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Communicating with database failed", "Check Passport Failed!", JOptionPane.ERROR_MESSAGE);
                    }
                    if(Passportavailable==true && custidofPassport.equals(this.lblCustId.getText())){
                        eiPassport.setVisible(false);
                        return true;
                    }
                    else if(Passportavailable==true && custidofPassport.equals(this.lblCustId.getText())==false){
                        eiPassport.setVisible(true);
                        eiPassport.setToolTipText("This Passport already exists!");
                        return false;
                    }
                    else if(Passportavailable==false){
                        eiPassport.setVisible(false);
                        return true;
                    }
                    else{
                        eiPassport.setVisible(true);
                        eiPassport.setToolTipText("This Passport already exists!");
                        return false;
                    }
                }
            }
            else{
                eiPassport.setVisible(true);
                eiPassport.setToolTipText("Invalid Passport!");
                return false;
            }
        }
    }
    
    public boolean cktxtAddress(){
        if(txtAddress.getText().equals("")){
            eiAddress.setVisible(true);
            eiAddress.setToolTipText("Empty Field!");
            return false;
        }
        else{
            if(txtAddress.getText().length()>100){
                eiAddress.setVisible(true);
                eiAddress.setToolTipText("Maximum characters exceed!");
                return false;
            }
            else{
                eiAddress.setVisible(false);
                return true;
            }
        }
    }
    
    public boolean cktxtCity(){
        if(txtCity.getText().equals("")){
            eiCity.setVisible(true);
            eiCity.setToolTipText("Empty Field!");
            return false;
        }
        else{
            if(txtCity.getText().length()>15){
                eiCity.setVisible(true);
                eiCity.setToolTipText("Maximum characters exceed!");
                return false;
            }
            else{
                eiCity.setVisible(false);
                return true;
            }
        }
    }
    
    public boolean ckGender(){
        if(this.radioMale.isSelected()){
            this.radioMale.setActionCommand("Male");
            eiGender.setVisible(false);
            return true;
        }
        else if(this.radioFemale.isSelected()){
            this.radioFemale.setActionCommand("Female");
            eiGender.setVisible(false);
            return true;
        }
        else{
            eiGender.setVisible(true);
            eiGender.setToolTipText("Not Selected!");
            return false;
        }
    }
    
    public boolean cktxtEmail(){
        
        int countAt=0;
        
        if(txtEmail.getText().equals("")){
            eiEmail.setVisible(true);
            eiEmail.setToolTipText("Empty Field!");
            return false;
        }
        else{
            if(txtEmail.getText().length()>50){
                eiEmail.setVisible(true);
                eiEmail.setToolTipText("Maximum characters exceed!");
                return false;
            }
            else{
                for(int x=0; x<txtEmail.getText().length();x++){
                    if(txtEmail.getText().charAt(x)=='@'){
                        countAt++;
                    }
                }
                if(countAt==1){
                    if(txtEmail.getText().endsWith("@")){
                        eiEmail.setVisible(true);
                        eiEmail.setToolTipText("Invalid email address!");
                        return false;
                    }
                    else{
                        eiEmail.setVisible(false);
                        return true;
                    }
                }
                else{
                    eiEmail.setVisible(true);
                    eiEmail.setToolTipText("Invalid email address!");
                    return false;
                }
            }
        }
    }
    
    public boolean cktxtContactno(){
        if(txtContactno.getText().equals("")){
            eiContactno.setVisible(true);
            eiContactno.setToolTipText("Empty Field!");
            return false;
        }
        else{
            if(txtContactno.getText().length()==10){
                if(txtContactno.getText().startsWith("0")==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else if(Character.isDigit(txtContactno.getText().charAt(1))==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else if(Character.isDigit(txtContactno.getText().charAt(2))==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else if(Character.isDigit(txtContactno.getText().charAt(3))==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else if(Character.isDigit(txtContactno.getText().charAt(4))==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else if(Character.isDigit(txtContactno.getText().charAt(5))==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else if(Character.isDigit(txtContactno.getText().charAt(6))==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else if(Character.isDigit(txtContactno.getText().charAt(7))==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else if(Character.isDigit(txtContactno.getText().charAt(8))==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else if(Character.isDigit(txtContactno.getText().charAt(9))==false){
                    eiContactno.setVisible(true);
                    eiContactno.setToolTipText("Invalid contact number!");
                    return false;
                }
                else{
                    eiContactno.setVisible(false);
                    return true;
                }
            }
            else{
                eiContactno.setVisible(true);
                eiContactno.setToolTipText("Invalid contact number!");
                return false;
            }
        }
    }
    
    public boolean cktxtDOB(){
        try{
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date = df.format(txtDOB.getDate());
            if(date.equals("")){
                eiDOB.setVisible(true);
                eiDOB.setToolTipText("Not Selected");
                return false;
            }
            else{
                eiDOB.setVisible(false);
                return true;
            }
        }
        catch(Exception exc){
            eiDOB.setVisible(true);
            eiDOB.setToolTipText("Invalid Date of Birth");
            return false;
        }
    }
    
    public boolean checkEntryDetails(){
        
        if(cktxtFname() & cktxtLname() & cktxtNIC() & cktxtPassport() & cktxtAddress() & cktxtCity() &cktxtDOB() & ckGender() & cktxtEmail() & cktxtContactno()){
            return true;
        }
        else{
            return false;
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddImage;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEditDetails;
    private javax.swing.JButton btnRemoveImage;
    private javax.swing.JButton btnSaveCustomer;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup btngrpGender;
    private javax.swing.JComboBox<String> combSearchType;
    private javax.swing.JLabel eiAddress;
    private javax.swing.JLabel eiCity;
    private javax.swing.JLabel eiContactno;
    private javax.swing.JLabel eiDOB;
    private javax.swing.JLabel eiEmail;
    private javax.swing.JLabel eiFname;
    private javax.swing.JLabel eiFname1;
    private javax.swing.JLabel eiGender;
    private javax.swing.JLabel eiLname;
    private javax.swing.JLabel eiNIC;
    private javax.swing.JLabel eiPassport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblCustId;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblPassport;
    private javax.swing.JLabel lblProfPic;
    private javax.swing.JPanel profilePic;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactno;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtSearchCust;
    // End of variables declaration//GEN-END:variables
    String imgpath = null;
    byte[] prof_img = null;
    Icon defprofimg;
}
